# Site settings
title: Yale Brainhack 2019
description: November 14th and 15th \n NeuroImprov!
#baseurl: brainhack2019 # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Yale Brainhack 2019
user_description: Welcome to Yale Brainhack 2019! To see available projects or suggest your own, please check out our <a href="https://groups.google.com/forum/#!forum/brainhack-yale-2019">google forum</a>. We'll provide food (breakfast+coffee, lunch from Tikkaway, snacks) to keep you going both days. Both days will end with a social to hang out/celebrate our successes. See below for location and timetable. 
user_title: November 14th and 15th
email: dave.oconnor@yale.edu
github_username:  YaleMRRC


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
